"use client";
import { useState } from "react";

type Tab = "crm" | "inbox" | "pilot" | "outreach";
const leads=[{company:"Intercom",signal:"Fin at production scale",value:"$36k",stage:"Qualified"},{company:"Glean",signal:"Agentic enterprise search",value:"$48k",stage:"Discovery"},{company:"Decagon",signal:"High-volume support agents",value:"$30k",stage:"Pilot ready"}];
const tabs:{id:Tab;n:string;title:string;subtitle:string}[]=[{id:"crm",n:"01",title:"Signal CRM",subtitle:"Who + why now"},{id:"inbox",n:"02",title:"Conversation → ticket",subtitle:"Turn words into action"},{id:"pilot",n:"03",title:"Pilot command center",subtitle:"Prove it fast"},{id:"outreach",n:"04",title:"Technical outreach",subtitle:"Earn the reply"}];
const SELF_EMAIL="kabith29@gmail.com";
function emailMyself(subject:string,body:string){const params=new URLSearchParams({view:"cm",fs:"1",to:SELF_EMAIL,su:subject,body});window.open(`https://mail.google.com/mail/u/0/?${params.toString()}`,"_blank","noopener,noreferrer")}

export default function Home(){const [tab,setTab]=useState<Tab>("crm");const [lead,setLead]=useState(0);const [routed,setRouted]=useState<number[]>([]);const [notice,setNotice]=useState("");const notify=(x:string)=>setNotice(x);return <main>
<header><div className="brand"><i/> MODA / GTM LAB</div><div className="header-right">PROOF OF WORK · PREPARED FOR PRANAV BEDI</div></header>
<nav className="top-nav"><button onClick={()=>document.getElementById("gtm-lab")?.scrollIntoView({behavior:"smooth"})}>GTM LAB</button><button onClick={()=>window.location.href="/demo"}>OPEN FULL DEMO →</button></nav>
<div id="gtm-lab"/><section className="intro"><div><p className="eyebrow">WHAT I WOULD BUILD FOR MODA</p><h1>Find the pain.<br/><em>Prove the value.</em><br/>Learn what to build.</h1></div><div className="why"><p className="eyebrow">WHY THIS HELPS MODA</p><p>One loop: the right customers, fast proof of value, and product insight.</p><b>Explore the working examples below</b></div></section>
<Flow/>
<section className="demo-shell"><nav className="demo-tabs">{tabs.map(x=><button key={x.id} className={tab===x.id?"selected":""} onClick={()=>setTab(x.id)}><span>{x.n}</span><b>{x.title}</b><small>{x.subtitle}</small></button>)}</nav><div className="workspace">{tab==="crm"&&<CRM lead={lead} setLead={setLead} notify={notify}/>} {tab==="inbox"&&<Inbox routed={routed} setRouted={setRouted} notify={notify}/>} {tab==="pilot"&&<Pilot notify={notify}/>} {tab==="outreach"&&<Outreach lead={leads[lead]} notify={notify}/>}</div>{notice&&<div className="demo-notice">✓ {notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}<footer className="impact"><span>WHAT THIS CREATES FOR MODA</span><strong>A repeatable customer-learning system: signal → conversation → pilot → proof.</strong></footer></section>
<section className="role"><p className="eyebrow">THE HYBRID ROLE I BRING</p><div className="role-grid"><article><span>GTM ENGINEER</span><h2>Create demand</h2><p>Signals, outreach, and a repeatable early funnel.</p></article><article><span>FORWARD DEPLOYED</span><h2>Create outcomes</h2><p>Focused pilots that connect traces to measurable fixes.</p></article><article><span>PRODUCT PARTNER</span><h2>Create learning</h2><p>Customer evidence that sharpens Moda’s product and ICP.</p></article></div></section>
</main>}

function Flow(){const steps=["Lead capture","Enrichment","Route & score","Technical outreach","Pilot & deploy","Product feedback"];return <section className="system-map"><div className="map-label"><span>THE MODA GTM ENGINE</span><p>From first signal to product insight.</p></div><div className="map-grid">{steps.map((x,i)=><article className="map-card" key={x}><div><i>{String(i+1).padStart(2,"0")}</i><b>{x}</b></div><span>{["Launches · hiring","Buyer · agent · pain","Fit · intent · volume","POV · email · discovery","Baseline · fix · proof","Tickets · insight · ICP"][i]}</span></article>)}</div></section>}
function CRM({lead,setLead,notify}:{lead:number;setLead:(n:number)=>void;notify:(x:string)=>void}){const x=leads[lead];return <div className="demo-content"><div className="topline"><div><span className="dot"/> SIGNAL CRM <small>LIVE ACCOUNT QUEUE</small></div><button className="new" onClick={()=>notify("Account capture started — add company, agent type, and signal.")}>+ Add account</button></div><div className="crm"><div className="lead-list"><p>HIGH-FIT ACCOUNTS <b>03</b></p>{leads.map((a,i)=><button key={a.company} className={i===lead?"active":""} onClick={()=>setLead(i)}><strong>{a.company}</strong><span>{a.stage}</span><em>{a.value}</em></button>)}</div><div className="lead-detail"><div className="company-row"><div className="logo">{x.company[0]}</div><div><h2>{x.company}</h2><p>{x.value} potential annual value</p></div><button onClick={()=>notify(`${x.company} CRM record opened.`)}>Open in CRM ↗</button></div><div className="info-cards"><div><span>WHY NOW</span><b>{x.signal}</b></div><div><span>PAIN</span><b>Agent reliability patterns before users feel them.</b></div><div><span>NEXT</span><b>Send POV → trace review.</b></div></div></div></div></div>}
function Inbox({routed,setRouted,notify}:{routed:number[];setRouted:(x:number[])=>void;notify:(x:string)=>void}){const items=[{n:"Jordan Lee",c:"Decagon",a:"Create pilot brief",q:"We can see tool-call errors, but cannot tell which workflow caused a resolution drop."},{n:"Priya Shah",c:"Glean",a:"Book technical discovery",q:"Long conversations lose earlier context and the team spends hours reading traces."}];const route=(i:number)=>{if(!routed.includes(i)){setRouted([...routed,i]);notify(`${items[i].a} created for ${items[i].c}.`)}};return <div className="demo-content"><div className="topline"><div><span className="dot"/> BUYER INTELLIGENCE <small>AI-ASSISTED INBOX</small></div><b className="status">{2-routed.length||"ALL"} SIGNALS NEED REVIEW</b></div><div className="inbox">{items.map((x,i)=>{const done=routed.includes(i);return <article className={done?"processed":""} key={x.n}><div className="person"><div>{x.n.split(" ").map(y=>y[0]).join("")}</div><p><b>{x.n}</b><span>{x.c} · Today</span></p><em>{done?"TICKET CREATED":"HIGH-INTENT"}</em></div><blockquote>“{x.q}”</blockquote><div className="ai-note"><span>MODA AI READ</span><p>Strong fit: route this reliability signal into the next customer action.</p><button disabled={done} onClick={()=>route(i)}>{done?"✓ Routed":`${x.a} →`}</button></div></article>})}</div></div>}
function Pilot({notify}:{notify:(x:string)=>void}){return <div className="demo-content"><div className="topline"><div><span className="dot"/> PILOT COMMAND CENTER <small>DECAGON / SUPPORT AGENT</small></div><b className="status">WEEK 2 OF 4</b></div><div className="pilot-head"><div><h2>From trace noise to<br/><em>validated improvement.</em></h2><p>One workflow. One measurable outcome.</p></div></div><div className="steps">{["Connect","Baseline","Fix","Prove"].map((x,i)=><div className={i<2?"complete":""} key={x}><span>0{i+1}</span><b>{x}</b><p>{i<2?"Complete":"Next"}</p></div>)}</div><div className="finding"><span>THIS WEEK’S FINDING</span><p>34% of bad outcomes include a failed knowledge-base tool call.</p><button onClick={()=>notify("Executive pilot readout generated.")}>Turn into exec readout ↗</button></div></div>}
function Outreach({lead,notify}:{lead:typeof leads[number];notify:(x:string)=>void}){const subject=`A question on ${lead.company}'s agent reliability loop`;const body=`Hi Kabith — this is the self-routed version of the ${lead.company} outreach.\n\nSignal: ${lead.signal}\n\nModa turns production traces into specific, fixable agent patterns. Would it be useful to compare notes?`;const copy=()=>{navigator.clipboard?.writeText(`Subject: ${subject}`);notify(`Outreach for ${lead.company} copied.`)};const send=()=>{emailMyself(subject,body);notify(`${lead.company} outreach opened in Gmail to ${SELF_EMAIL}.`)};return <div className="demo-content"><div className="topline"><div><span className="dot"/> OUTREACH STUDIO <small>TECHNICAL + PERSONALIZED</small></div><div className="outreach-actions"><button className="new" onClick={copy}>Copy</button><button className="new send-self" onClick={send}>Email myself ↗</button></div></div><div className="outreach"><aside><p>INPUTS</p><div><span>ACCOUNT</span><b>{lead.company}</b></div><div><span>SIGNAL</span><b>{lead.signal}</b></div><div><span>RECIPIENT</span><b>{SELF_EMAIL}</b></div></aside><article><p className="label">GENERATED FIRST TOUCH · SAFE SELF-SEND</p><h3>Subject: {subject}</h3><p>Hi Kabith — this is the self-routed version of the {lead.company} outreach. Moda turns production traces into specific, fixable agent patterns. Would it be useful to compare notes?</p><div className="message-footer"><span>Original prospect context preserved</span><span>Recipient: you</span></div></article></div></div>}
function FullDemo(){const [s,setS]=useState(0);const scenes=["A new agent signal appears.","Build a clear pain hypothesis.","Earn the technical conversation.","Prove one measurable outcome.","Feed evidence into product."];return <section id="full-demo" className="full-demo"><div className="full-head"><div><p className="eyebrow">FULL DEMO / THE OPERATING LOOP</p><h2>From first signal to<br/><em>customer proof.</em></h2></div><p>Click through the GTM motion.</p></div><div className="demo-run"><aside>{scenes.map((_,i)=><button className={s===i?"active":""} onClick={()=>setS(i)} key={i}><span>0{i+1}</span><b>{["FIND","UNDERSTAND","ENGAGE","PROVE","LEARN"][i]}</b></button>)}</aside><article><p className="scene-count">STEP 0{s+1} / 05</p><h3>{scenes[s]}</h3><div className="scene-card"><span className="scene-dot"/><p>{["Decagon launches high-volume AI support agents.","Likely pain: tool-call failures reduce resolution quality.","Send a technical point of view grounded in their signal.","Connect one workflow and quantify the failure pattern.","Create proof, a product ticket, and the expansion path."][s]}</p></div><button className="scene-action" onClick={()=>setS((s+1)%5)}>Continue <span>→</span></button></article></div></section>}
